name: stackgan-hiv
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - numpy
  - pandas
  - matplotlib
  - pillow
  - scikit-image
  - scikit-learn
  - tqdm
  - pip
  - pip:
      - transformers
      - biopython
      - py3Dmol
